In [3]:
from mxnet import nd

In [4]:
x = nd.array([3.0])
y = nd.array([2.0])
print(x+y)
print(x*y)
print(x/y)
print(nd.power(x, y))


[5.]
<NDArray 1 @cpu(0)>

[6.]
<NDArray 1 @cpu(0)>

[1.5]
<NDArray 1 @cpu(0)>

[9.]
<NDArray 1 @cpu(0)>


In [5]:
print(x)


[3.]
<NDArray 1 @cpu(0)>


In [7]:
# Don't do this often. This basically halts any operation being done on 
# NDArray x because now python is taking over, which is bad in parallel 
# processing.
print(x.asscalar())

3.0


In [8]:
x = nd.arange(5)
x


[0. 1. 2. 3. 4.]
<NDArray 5 @cpu(0)>

In [9]:
x[3]


[3.]
<NDArray 1 @cpu(0)>

In [10]:
x.shape

(5,)

In [11]:
len(x)

5

In [13]:
# scalar multiplication, addition
a = 2
x = nd.array([1,2,3])
y = nd.array([10,20,30])
print(a*x)
print(a*x + y)


[2. 4. 6.]
<NDArray 3 @cpu(0)>

[12. 24. 36.]
<NDArray 3 @cpu(0)>


In [14]:
print(nd.arange(10))


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<NDArray 10 @cpu(0)>


In [15]:
A = nd.arange(20).reshape((10,2))
A


[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]
 [12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]]
<NDArray 10x2 @cpu(0)>

In [16]:
A = nd.arange(20).reshape((2, 10))

In [17]:
A


[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
<NDArray 2x10 @cpu(0)>

In [18]:
A.T


[[ 0. 10.]
 [ 1. 11.]
 [ 2. 12.]
 [ 3. 13.]
 [ 4. 14.]
 [ 5. 15.]
 [ 6. 16.]
 [ 7. 17.]
 [ 8. 18.]
 [ 9. 19.]]
<NDArray 10x2 @cpu(0)>

In [19]:
X = nd.arange(24).reshape((2,3,4))
print(X.shape)
print(X)

(2, 3, 4)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
<NDArray 2x3x4 @cpu(0)>


In [20]:
x = nd.ones(3)

In [21]:
x


[1. 1. 1.]
<NDArray 3 @cpu(0)>

In [22]:
print(nd.sum(x))


[3.]
<NDArray 1 @cpu(0)>


In [23]:
x = nd.arange(12).reshape((3,4))
print(x)
print(nd.sum(x))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[66.]
<NDArray 1 @cpu(0)>


In [32]:
# Use -1 to fill in defaults
x = nd.arange(12)
print(x.reshape((3, -1))) # This would pick 4 as second index because x has a total of 12 elements.
print(x.reshape((-1, 6))) # This would pick 2 as first index as x has total 12 elements and you requested 6 as second index


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
<NDArray 2x6 @cpu(0)>


In [24]:
print(nd.sum(x, 1))


[ 6. 22. 38.]
<NDArray 3 @cpu(0)>


In [25]:
print(nd.sum(x, 0))


[12. 15. 18. 21.]
<NDArray 4 @cpu(0)>


In [26]:
nd.mean(x)


[5.5]
<NDArray 1 @cpu(0)>

In [27]:
x = nd.arange(4) + 1.0
y = nd.ones(4)
nd.dot(x, y)


[10.]
<NDArray 1 @cpu(0)>

In [28]:
# L2 norm
nd.norm(x)


[5.477226]
<NDArray 1 @cpu(0)>

In [29]:
# L1 norm
nd.sum(nd.abs(x))


[10.]
<NDArray 1 @cpu(0)>

In [34]:
nd.empty((3,4)) # Will grab some part of memory and assign back. Not cleaning.


[[ 8.9913196e+21  4.5567423e-41  1.4437365e-38  0.0000000e+00]
 [-8.7874729e+14  2.7497668e+07  8.9879779e+21  4.5567423e-41]
 [ 1.4437365e-38  0.0000000e+00  1.6331850e-02 -4.3323472e+05]]
<NDArray 3x4 @cpu(0)>

In [35]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [37]:
nd.ones((3,4,5))


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
<NDArray 3x4x5 @cpu(0)>

In [39]:
nd.array([[1,2,3],[2,3,4],[3,4,5]])


[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]]
<NDArray 3x3 @cpu(0)>

In [53]:
rarray = nd.random.normal(0, 1, shape=(100,100))
nd.mean(rarray)


[0.00123111]
<NDArray 1 @cpu(0)>

In [54]:
rarray


[[-1.2106425  -1.024502   -1.5847118  ...  1.2321575  -1.4030455
   0.70266616]
 [-0.08494543 -0.81021076  0.75389177 ... -0.80285645 -1.8379554
  -0.24725795]
 [ 0.62455493  1.668636   -0.10974155 ...  1.0206766   0.03574003
   1.8067027 ]
 ...
 [ 0.06561311  1.7734725  -1.5847464  ...  1.0460557  -0.5302033
   0.18293837]
 [ 1.7936301   0.08462477 -0.58066535 ...  0.3258385  -1.832737
  -2.0320733 ]
 [-0.57903296 -1.6637332  -1.2882146  ...  1.2612616  -0.5646808
   1.1529359 ]]
<NDArray 100x100 @cpu(0)>

In [64]:
x = nd.array([1,2,3,4])
y = nd.ones_like(x) * 2

In [65]:
x


[1. 2. 3. 4.]
<NDArray 4 @cpu(0)>

In [66]:
y


[2. 2. 2. 2.]
<NDArray 4 @cpu(0)>

In [58]:
x.exp()


[ 2.7182817  7.389056  20.085537  54.59815  ]
<NDArray 4 @cpu(0)>

In [59]:
nd.concat(x, y, dim=0) # or dim=1


[1. 2. 3. 4. 2. 2. 2. 2.]
<NDArray 8 @cpu(0)>

In [62]:
x.norm().asscalar()

5.477226

In [63]:
import numpy as np

In [67]:
a = x.asnumpy()
print(type(a))
b = nd.array(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'mxnet.ndarray.ndarray.NDArray'>
